version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - network

  web:
    image: nginx:alpine
    restart: always
    working_dir: /usr/share/nginx/html
    networks:
      - network
    ports:
    - 8080:80
    depends_on:
      - app
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/nginx:/etc/nginx/conf.d
networks:
  network: